title: Wiley's Page

theme: jekyll-theme-primer

defaults:
    -
        scope:
            path: ""
        values:
            category: ""
            collection_url: /
            css_url: style.css
            layout: "base"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "posts"
    -
        scope:
            path: "tags"
        values:
            layout: "tags"
    -
        scope:
            path: "tags/index.md"
        values:
            layout: "base"
    -
        scope:
            path: "modern"
        values:
            category: "modern"
            collection_url: /modern/
            css_url: modernstyle.css
            layout: "modernbase"
    -
        scope:
            path: "modern"
            type: "posts"
        values:
            layout: "modernposts"
    -
        scope:
            path: "modern/tags"
        values:
            layout: "moderntags"
    -
        scope:
            path: "modern/tags/index.md"
        values:
            layout: "modernbase"

exclude: [
    /vendor/,
    CNAME,
    Gemfile,
    Gemfile.lock,
]

plugins:
    - jekyll-relative-links
    - jekyll-sitemap

relative_links:
  enabled: true
  collections: true
